source 'https://rubygems.org'

gem 'ffi'
gem 'jekyll', '~> 4.3.2'

group :jekyll_plugins do
  gem 'html-proofer'
  gem 'jekyll-assets', git: 'https://github.com/envygeeks/jekyll-assets'
  gem 'jekyll_draft'
  gem 'jekyll-environment-variables'
  gem 'jekyll-feed'
  gem 'jekyll_from_to_until', path: '../'
  gem 'jekyll-sitemap'
  gem 'jekyll-sort'
  gem 'jekyll-tagging'
  gem 'kramdown'
end

group :test, :development do
  gem 'debug', '>= 1.0.0', require: false
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-md', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
  gem 'ruby-debug-ide', require: false
end
